[workspace]
authors = ["Tim de Jager <tdejager89@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
name = "test-wax"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
main = "cargo run"
test = "cargo test"
bench = {cmd = "cargo bench --bench wax_vs_ignore", depends-on = ["test"] }
bench-no-test = {cmd = "cargo bench --bench wax_vs_ignore"}
opencv-src = "mkdir -p external && git clone --depth 1 https://github.com/opencv/opencv.git external/opencv"

[dependencies]
# This is just to fill up space
python = ">=3.13.7,<3.14"
compilers = ">=1.11.0,<2"
cmake = ">=4.1.1,<5"
opencv = ">=4.12.0,<5"
# This we can use to compile
rust = ">=1.89.0,<1.90"
